create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  display_name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  level text not null,
  score integer not null,
  total integer not null,
  percent integer not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.subnet_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  mode text not null,
  difficulty text,
  score integer not null,
  total integer not null,
  time_seconds integer,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.lab_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  lab_id text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint lab_completions_user_lab_key unique (user_id, lab_id)
);

create table if not exists public.lab_step_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  lab_id text not null,
  steps_json jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint lab_step_progress_user_lab_key unique (user_id, lab_id)
);

create index if not exists quiz_attempts_user_id_idx on public.quiz_attempts (user_id, created_at desc);
create index if not exists subnet_attempts_user_id_idx on public.subnet_attempts (user_id, created_at desc);
create index if not exists lab_completions_user_id_idx on public.lab_completions (user_id, created_at desc);
create index if not exists lab_step_progress_user_id_idx on public.lab_step_progress (user_id);

alter table public.profiles enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.subnet_attempts enable row level security;
alter table public.lab_completions enable row level security;
alter table public.lab_step_progress enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles
  for select
  using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  using (auth.uid() = id);

drop policy if exists "quiz_attempts_all_own" on public.quiz_attempts;
create policy "quiz_attempts_all_own"
  on public.quiz_attempts
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "subnet_attempts_all_own" on public.subnet_attempts;
create policy "subnet_attempts_all_own"
  on public.subnet_attempts
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "lab_completions_all_own" on public.lab_completions;
create policy "lab_completions_all_own"
  on public.lab_completions
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "lab_step_progress_all_own" on public.lab_step_progress;
create policy "lab_step_progress_all_own"
  on public.lab_step_progress
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
